// @flow
export const SET_ACTIVE_PERSON: 'SET_ACTIVE_PERSON' = 'SET_ACTIVE_PERSON';
export const SET_SIG_EL: 'SET_SIG_EL' = 'SET_SIG_EL';
export const SET_NEW_PERSON_ACTIVE: 'SET_NEW_PERSON_ACTIVE' = 'SET_NEW_PERSON_ACTIVE';
export const SET_NEW_PERSON: 'SET_NEW_PERSON' = 'SET_NEW_PERSON';
export const SET_GENERATE: 'SET_GENERATE' = 'SET_GENERATE';
